<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LevelManager</RootNamespace>
    <UseWPF>true</UseWPF>
    <AssemblyName>LevelManager</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Title>LevelManager</Title>
    <Description>Revit Level Manager add-in</Description>
    <Copyright>codehaks</Copyright>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <Import Project="..\Shared\Shared.projitems" Label="Shared" />

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="LevelManager.addin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
